apiVersion: v1
kind: PersistentVolume
metadata:
  name: manzanas-persistent-storage
  namespace: andesgt
  labels:
    app: manzanas
    tier: backend
spec:
  storageClassName: manual
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/c/Users/RafaelVelez/Documents/agtdemo/mock/manzanas"
