apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-persistent-storage
  namespace: andesgt
  labels:
    app: web
    tier: backend
spec:
  storageClassName: manual
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/c/Users/RafaelVelez/Documents/agtdemo/portal"