apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-persistent-storage
  namespace: andesgt
  labels:
    app: web
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi